FROM arm32v7/debian:bookworm

RUN apt-get update && apt-get install -y \
    build-essential \
    libsdl2-dev \
    libdrm-dev \
    libgbm-dev \
    autoconf \
    git \
    pkg-config \
    sudo \
    && rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/WiringPi/WiringPi.git /tmp/WiringPi \
    && cd /tmp/WiringPi \
    && ./build \
    && ldconfig

WORKDIR /work
COPY . .

RUN make clean && make
