#!/bin/bash
ROM=`cat ./romfile`
choice=$(./msxrom $ROM)
if [ -z $choice ]; then 
	tput cvvis
	exit
fi
echo $choice > ./romfile
ROM=`ls *cart/*$choice.zip *cart/*$choice.rom | sed -n 1p`
if [ -z $ROM ]; then
	./r
	exit
else
	if [[ $ROM == *"msx2"* ]]; then
		msx="MSX2"
	else
		msx=""
	fi	
	echo ./r \"$msx\" /rom1 $ROM > xy
	./r "$msx" /rom1 $ROM
fi
